
=head1 Intruction

A poker game server for Gan Deng Yan(gdy).

 var http=require('http');

=head1 Dependcies

=over

=item 1. Node.js(0.6.2)

=item 1. SQLite3

=item 1. HTML5

=item 1. Prototype

=back

=head1 Development Tools

=over

=item * Emacs

=item * Git

=back


=head1 Licence

=over

MIT license 

=back

=head1 Authors

=over

canw, eggcaker

=back

